### ISSUE TITLE
Choose between u = r/h or q = r / (N*h)

### ISSUE THREAD

**Issue by LudwigBoess** [LudwigBoess/SPHKernels.jl#13]
As discussed in #11 we should decide how to proceed with the kernel definition.

Currently the package follows the convention of for example [Gadget](http://articles.adsabs.harvard.edu/pdf/2005MNRAS.364.1105S), which is uncommon compared to other SPH codes.
( For a discussion on this see e.g. [Dehnen & Aly (2012)](https://watermark.silverchair.com/425-2-1068.pdf?token=AQECAHi208BE49Ooan9kkhW_Ercy7Dm3ZL_9Cf3qfKAc485ysgAAAtkwggLVBgkqhkiG9w0BBwagggLGMIICwgIBADCCArsGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMW6jPRrYs3vsl5uAdAgEQgIICjDAGiaJLvOXyfki7xUzxnyozwt8dqeWuTkj1ZdNv91FVK6A4HAGt756j663fI9JqIvjUeOMxzarj9JpmztOKwbRGDx9wYdWGQqGu64ObXzUiuu2G9Zn-dDhfNaxYmq9F7JrLFT_48NKiUwsS8PIZka82dmI6ZPTI-B-Ta4G-lQ8dWizAiwrmqEHjkLhIGq9mUbCZVI9WMgk3uHYZjxAN0yb12VPRXLFkXfcPls_9Mlg_-jSRf1eG77mQuz5Q8R1NVGcWZ8F345RtuTm_Rz1jKO6PE4MfYJuxyxA8wlT117akpCvR98bLVwcKzxbCVK0yyIhXr37YJqhJq9KyKKtKgAQdXRqsl9FS2yXZ6LqbYBNjW-oXiwPUn0hSb03K5d-CmJ_wWREWsh2yFpjYDYqliQYIJeBrDKbUwCM1EzFkFmvwEIKpGVldpUvTBmamSu8WK8CkmujGwsL6AA1UQ_A0QntrVDii9UOYA_Kmj8c4eEyi9czRIODVv6gONXUdHMOftL_60z5yJHQ6kt0zVri3gjITmoiieD8cPr00E8EnRmRFPrGQP0DLOkIQZF7lQET-GAfT48X8wjSH9eb5XY0TO91Rnma3USgbPc1YzXDvIue2FIv5Q2f8kCQK3plbNIaYWSJNO4k6IU-x2WOi-_bBMvGmzwiMVtUBJFhOc7lktuDTl_ZBM4t6AjmpxkAY6j0TeBrQj2AFoOBcdlpmeCEAACi4YmBWQmwXEGa0eJJjk8xwe99oXIYvvRty5jGm7TwN6Fh1HrbuhuMeKV9J9Ev-yRsr24lvwhzcWAC5bRIHDkswlbTOgkjfPKnbRezEMseYsob-M_cTERcfgQuitBZiBa-ho2cig7HXyNHMdYo), Section 2. )

This convention has the advantage of making the switch between kernels easier, for example in the neighbour search (to my knowledge, feel free to prove me wrong!).

**Comment by AhmedSalih3d** [comment]
Hi again

I do not intend to comment more on this now as agreed in #11, but I want to highlight the Dehnen & Aly link is not working for me:

`Your session has timed out. Please go back to the article page and click the PDF link again.` 

And I would like to read it :) 

You have a valid point that for the neighbour search algorithm, having a unified kernel formulation would make that easier. Perhaps we should make a pro and cons list in a few weeks from now (to allow space for thoughts to form)

Kind regards

**Comment by LudwigBoess** [comment]
Oh, sorry about the link and thanks for letting me know! :)

This one should work: [Dehnen & Aly (2012)](https://arxiv.org/abs/1204.2471)

**Comment by OndrejKincl** [comment]
Hi, I just wanted to say that I also prefer the convention of Gadget, so you are not alone. (Only that I don't call h smoothing length but support radius to avoid confusion. )  I authored SmoothedParticles.jl package where I put into documentation that the package is compatible with SPHkernels.jl. I would not be very happy if the convention suddenly changed. Of course, it would be totally fine as a backward-compatible optional variant.

**Comment by LudwigBoess** [comment]
I'm closing this issue for now, let's stick to the Gadget convention until major arguments against it come up.
