### ISSUE TITLE
Non normalize methods

### ISSUE THREAD

**Issue by PharmCat** [LudwigBoess/SPHKernels.jl#32]
Hi! I try to apply SPHKernels.jl  for GPU kernel but for performance purpose it important to get only result of kernel function, and make multiplication   `kernel.norm * h_inv` after summation. 

```
function kernel_value(kernel::WendlandC2_1D{T}, u::Real, h_inv::Real) where {T}

    if u < 1
        n = kernel.norm * h_inv
        t1 = 1 - u
        t3 = t1 * t1 * t1
        return (t3 * (1 + 3u)) * n |> T
    else
        return 0 |> T
    end

end
```

is it possible to make method like that?:

```
function kernel_value(kernel::WendlandC2_1D{T}, u::Real, h_inv::Real, norm::Bool = true) where {T}
    if u < 1
        t1 = 1 - u
        t3 = t1 * t1 * t1
        val = t3 * (1 + 3u)
        ifelse(norm, return val  * kernel.norm * h_inv, return val) |> T  # `|> T`   this is potential issue for ForwardDiff and have few sense 
    end
    return zero(T)
end
```

so actually need method to get normalization constant for each function.

**Comment by LudwigBoess** [comment]
Again sorry I missed this:
I split the `kernel_value` function into two: `kernel_value(kernel, u, h_inv)` applies the nomalisation, `kernel_value(kernel, u)` does not.
This avoids performance overhead.
Can you please chheck in the branch rc2.3.0 if this solution works for you?
