### ISSUE TITLE
Question about x/h and h_inv

### ISSUE THREAD

**Issue by AhmedSalih3d** [LudwigBoess/SPHKernels.jl#8]
Hello!

Thank you very much for making this package, I am trying to use it for some calculations. 

This way of defining smoothing kernels is a bit new for me, in the sense that I have only seen kernels previously where "2h" (2 times the smoothing length) is the defining factor.

Therefore I am a bit confused of what I actually need to insert as value for x/h and h_inv.

I am trying to use WendlandC4 in 2D, where I have:

h = 0.04 m. 

According to the notation used in Dehnen and Aly's paper, I suppose I should use;

x/u = x/(2*h)

h_inv = 1/(2*h)

But when I test this I get wrong results. 

Would you mind clearing up my confusion?

Kind regards, Ahmed

**Comment by LudwigBoess** [comment]
Hi Ahmed,

please excuse the late reply, I neglected this package a little and only just saw the issue.

I checked and there was unfortunately quite a severe (and stupid) bug in the C4 kernel.

Can you please update to version 1.4 and check if you still get a wrong result? 

Cheers,
Ludwig

**Comment by LudwigBoess** [comment]
closing this for now

**Comment by AhmedSalih3d** [comment]
Hi again

I am looking into this again, sorry for not having answered earlier.

Based on your first comment, my understanding is that now everything should follow "conventional" notion of having q = r/h, where r is the Euclidean distance, h is smoothing length?

I am not that familiar with the kernels you have implemented so I will try to extend with one I know well as mentioned in your docs. I think it could be very interesting to have this kind of SPHKernel library you already have been working hard on.

Kind regards
